### ISSUE TITLE
error when starting from scratch

### ISSUE THREAD

**Issue by e-genov-ks** [vgo-exo/node-red-contrib-flow-splitter#3]
Error with v2, when node-red starts.
Exception: 
`[error] TypeError: Cannot read properties of undefined (reading 'then')
2024-12-10T10:57:12.209679847Z     at Object.registerMessageCatalog (/usr/src/node-red/node_modules/@node-red/runtime/node_modules/@node-red/util/lib/i18n.js:50:24)
2024-12-10T10:57:12.209682055Z     at Object.start (/usr/src/node-red/node_modules/@node-red/runtime/lib/index.js:135:17)
2024-12-10T10:57:12.209683305Z     at Object.start (/usr/src/node-red/node_modules/node-red/lib/red.js:105:36)
2024-12-10T10:57:12.209684639Z     at /usr/src/node-red/node_modules/node-red/red.js:483:9
`
Steps to reproduce: 

Dockerfile
```
FROM nodered/node-red:4.0.5
RUN yarn add node-red-contrib-flow-splitter@2.0.2
``` 
Docker-compose 
```
services:
  nodered:
    build:
      dockerfile: Dockerfile
    ports:
      - "1880:1880"
    volumes:
      - ./:/data
```

Command for start: 
`docker-compose up`
